### ISSUE TITLE
Furnace style crafting option.

### ISSUE THREAD

**Issue by Shrimpstress** [TeamAOF/Artis#13]
Allow users to set Artis tables to a custom version that requires crafting time whenever it crafts an item. The crafting time would be designated by the recipes for that table (and could be set to 0 for instant craft).

**Comment by Nathan22211** [comment]
furnace style? I was thinking you could make the ability to add custom furnace types with this mod

**Comment by Shrimpstress** [comment]
I'm closing this because I agree, I do think just implementing custom furnaces would be the better idea here.
