### ISSUE TITLE
You can see through the world at the feet of the test table

### ISSUE THREAD

**Issue by Trnrr** [TeamAOF/Artis#14]
Place a test table on the ground and it shows the caves below it. I just used the test template off the wiki. 
 

>  "tables": {
>     "artis:test_table": {
>       "width": 4,
>       "height": 3,
>       "generate_assets": true,
>       "color": "#7F76D1"
>     }
>   }

**Comment by Shrimpstress** [comment]
I'll add the ability to mark a table as non opaque in the next update, should fix this issue.

**Comment by Shrimpstress** [comment]
A PR for this has been merged, I'll close this once a new build is released.

**Comment by LemmaEOF** [comment]
@Trnrr For your table, you now want:
```json5
{
  "tables": {
    "artis:test_table": {
      "width": 4,
      "height": 3,
      "generate_assets": true,
      "color": "#7F76D1",
      "settings": {
        "non_opaque": true
      }
    }
  }
}
```

**Comment by Trnrr** [comment]
> 
> 
> @Trnrr For your table, you now want:
> 
> ```js
> {
>   "tables": {
>     "artis:test_table": {
>       "width": 4,
>       "height": 3,
>       "generate_assets": true,
>       "color": "#7F76D1",
>       "settings": {
>         "non_opaque": true
>       }
>     }
>   }
> }
> ```

Ok thank you. I will do this
