### ISSUE TITLE
1.18 Port

### ISSUE THREAD

**Issue by DaFuqs** [TeamAOF/Artis#25]
Dunno if this is even relevant for you anymore, but I created a port for 1.18.1 here: https://github.com/DaFuqs/Artis
I will have to update some docs, still, but otherwise it is finished and fully usable.

Feel free to upstream my branch to yours, if you like :)
Since I want to make this version available for packs (the whole port was a request for a pack maker): You want to release a version on the original Curseforge/Modrinth pages, or would you prefer I change the name a bit and just link to your original version?

**Comment by Shrimpstress** [comment]
Either/or is fine. I was considering a port to 1.18 recently but I have not had the time to work on it, so it’s likely I wouldn’t be available to do much maintenance work on it after a port.

**Comment by Shrimpstress** [comment]
I’ll take a look at the port later when I’m not at work and I’ll decide what I’d like to do, if
that’s fine with you.

**Comment by DaFuqs** [comment]
Absolutely, thank you!

**Comment by DaFuqs** [comment]
Oh yeah, a few things that I should mention while I have them on my mind:
- The mod you previously used to inject textures is dead, it seems. It is handled with ARRP now
- The config layout changed a bit, because things like breakability is handled via block tags instead of block settings in vanilla now
- Since I have no experience with KubeJS that part of the code is removed currently. Recipes are set via data pack only.
- There are no red slots, currently
- Someone mentioned that catalysts were a bit borked the last time? I never played your original, but they do work in this version
